# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/LanguageConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/LanguageConfig.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1aproto/LanguageConfig.proto\x12\x05proto\"+\n\x0eLanguageConfig\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\r\n\x05Value\x18\x02 \x01(\t\"\x8c\x01\n\x11LanguageConfigMap\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.proto.LanguageConfigMap.ItemsEntry\x1a\x43\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.proto.LanguageConfig:\x02\x38\x01\x62\x06proto3')
)




_LANGUAGECONFIG = _descriptor.Descriptor(
  name='LanguageConfig',
  full_name='proto.LanguageConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='proto.LanguageConfig.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Value', full_name='proto.LanguageConfig.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=80,
)


_LANGUAGECONFIGMAP_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='proto.LanguageConfigMap.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.LanguageConfigMap.ItemsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.LanguageConfigMap.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=223,
)

_LANGUAGECONFIGMAP = _descriptor.Descriptor(
  name='LanguageConfigMap',
  full_name='proto.LanguageConfigMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='proto.LanguageConfigMap.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LANGUAGECONFIGMAP_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=223,
)

_LANGUAGECONFIGMAP_ITEMSENTRY.fields_by_name['value'].message_type = _LANGUAGECONFIG
_LANGUAGECONFIGMAP_ITEMSENTRY.containing_type = _LANGUAGECONFIGMAP
_LANGUAGECONFIGMAP.fields_by_name['items'].message_type = _LANGUAGECONFIGMAP_ITEMSENTRY
DESCRIPTOR.message_types_by_name['LanguageConfig'] = _LANGUAGECONFIG
DESCRIPTOR.message_types_by_name['LanguageConfigMap'] = _LANGUAGECONFIGMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LanguageConfig = _reflection.GeneratedProtocolMessageType('LanguageConfig', (_message.Message,), dict(
  DESCRIPTOR = _LANGUAGECONFIG,
  __module__ = 'proto.LanguageConfig_pb2'
  # @@protoc_insertion_point(class_scope:proto.LanguageConfig)
  ))
_sym_db.RegisterMessage(LanguageConfig)

LanguageConfigMap = _reflection.GeneratedProtocolMessageType('LanguageConfigMap', (_message.Message,), dict(

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _LANGUAGECONFIGMAP_ITEMSENTRY,
    __module__ = 'proto.LanguageConfig_pb2'
    # @@protoc_insertion_point(class_scope:proto.LanguageConfigMap.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _LANGUAGECONFIGMAP,
  __module__ = 'proto.LanguageConfig_pb2'
  # @@protoc_insertion_point(class_scope:proto.LanguageConfigMap)
  ))
_sym_db.RegisterMessage(LanguageConfigMap)
_sym_db.RegisterMessage(LanguageConfigMap.ItemsEntry)


_LANGUAGECONFIGMAP_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
